import tkinter
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Label, Button, PhotoImage
import  webbrowser


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/GitHub/aboba/authorization/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class EntryWithPlaceholder(Entry):
    def __init__(self, master=None, placeholder=None, **kw):
        Entry.__init__(self, master, kw)
        # super().__init__(master)


        if placeholder is not None:
            self.placeholder = placeholder
            self.placeholder_color = '#D1D1D1'
            self.default_fg_color = self['fg']

            self.bind("<FocusIn>", self.focus_in)
            self.bind("<FocusOut>", self.focus_out)

            self.put_placeholder()

    def put_placeholder(self):
        self.insert(4, self.placeholder)
        self['fg'] = self.placeholder_color

    def focus_in(self, *args):
        if self['fg'] == self.placeholder_color:
            self.delete('0', 'end')
            self['fg'] = self.default_fg_color
            self.configure(show='*')

    def focus_out(self, *args):
        if not self.get():
            self.put_placeholder()
            self.configure(show='')


class ImageButton(Button):
    def __init__(self, master, image1, image2, *args, **kwargs):
        self.unclickedImage = PhotoImage(file = image1)
        self.clickedImage = PhotoImage(file = image2)
        super().__init__(master, *args, image = self.unclickedImage, **kwargs)
        self.bind("<Button-1>", self.active_button)
        self.bind("<ButtonRelease>", self.normal_button)
    def active_button(self, event=None):
        if self.cget("state") != "disabled":
            self.config(image=self.clickedImage)
    def normal_button(self, Event=None):
        if self.cget("state") != "disabled":
            self.config(image=self.unclickedImage)


window = Tk()

window.geometry("1360x758")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)


def callback(url):
    webbrowser.open_new(url)


def canvas_clicked(event):
    current = event.widget.find_withtag("current")
    clicked_tags = canvas.gettags(current)
    if 'link' in clicked_tags:
        callback('file:///home/ramina/Документы/GitHub/aboba/authorization/forgot_password.html')


canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    717.0,
    512.0,
    image=image_image_2
)

canvas.create_text(
    561,
    293,
    anchor="nw",
    text="Авторизация",
    fill="#FFFFFF",
    font=("Inter", 48 * -1)
)

canvas.create_text(
    632,
    638,
    anchor="nw",
    text="Забыли пароль?",
    fill="#FFFFFF",
    font=("Inter", 20 * -1),
    tags='link'
)

# text = Label(
#     632,
#     638,
#     anchor="nw",
#     text="Забыли пароль?",
#     fill="#FFFFFF",
#     font=("Inter", 20 * -1)
# )
canvas.bind("<Button-1>", canvas_clicked)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
# button_1 = Button(
#     image=button_image_1,
#     borderwidth=0,
#     highlightthickness=0,
#     command=lambda: print("button_1 clicked"),
#     relief="flat"
# )
# button_image_2 = PhotoImage(
#     file=relative_to_assets("button_2.png"))
# button_1 = IButton(
#     image=button_image_1,
#     borderwidth=0,
#     highlightthickness=0,
#     command=pressed(PhotoImage(file=relative_to_assets("button_2.png"))),
#     relief="flat"
# )
button = ImageButton(window, relative_to_assets("button_1.png"),
                    relative_to_assets("button_2.png"),
                    borderwidth=0,
                    highlightthickness=0,
                    relief="flat"
                    )
# button_1.configure(command=pressed(button_1, PhotoImage(file=relative_to_assets("button_2.png"))))
button.place(
    x=567.0,
    y=676.0,
    width=307.0,
    height=51.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    720.5,
    428.0,
    image=entry_image_1
)
# entry_1 = Entry(
#     bd=0,
#     bg="#FFFFFF",
#     fg="#000716",
#     highlightthickness=0
# )
entry_1 = EntryWithPlaceholder(
    window, 'Введите пользователя', bd=0, bg="#806592", fg='#FFFFFF',
    highlightthickness=0, insertbackground='#FFFFFF', font='Calibri 13'
)
entry_1.place(
    x=620.0,
    y=413.0,
    width=240.0,
    height=30.0
)

canvas.create_text(
    565,
    373,
    anchor="nw",
    text="Пользователь",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    594.96435546875,
    427.0,
    image=image_image_3
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    720.5,
    548.5,
    image=entry_image_2
)
# entry_2 = Entry(
#     bd=0,
#     bg="#FFFFFF",
#     fg="#000716",
#     highlightthickness=0
# )
entry_2 = EntryWithPlaceholder(
    window, 'Введите пароль', bd=0, bg="#806592", fg='#FFFFFF',
    highlightthickness=0, insertbackground='#FFFFFF', font='Calibri 13'
)
entry_2.place(
    x=620.0,
    y=534.0,
    width=240.0,
    height=30.0
)

canvas.create_text(
    566,
    493,
    anchor="nw",
    text="Пароль",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    592.0,
    547.0,
    image=image_image_4
)

# window.resizable(False, False)
window.mainloop()
